### PR TITLE
remove ember-data pin

### PR DESCRIPTION
**Pull request by kellyselden**
Tracked here https://github.com/emberjs/data/issues/4961

### CODE REVIEW

**Comment by runspired** [comment]
Can you point to what's failing?

**Comment by kellyselden** [comment]
@runspired I'm guessing the usage of a promise macro:

https://github.com/kellyselden/ember-tree/blob/master/tests/dummy/app/components/ember-data.js#L86
https://github.com/kellyselden/ember-tree/blob/master/tests/dummy/app/components/ember-data.js#L100
https://github.com/kellyselden/ember-tree/blob/master/tests/dummy/app/components/ember-data.js#L111

Which uses https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/promise/-utils.js#L16

The difference between ember-data versions is whether the get is called before the set here? https://github.com/emberjs/ember.js/blob/299c1ab3d804fd92b0ec9b9c2e7a1fa100335753/packages/ember-runtime/lib/mixins/promise_proxy.js#L162-L169

**Comment by runspired** [comment]
@kellyselden thanks I'll see if I can pin down

**Comment by kellyselden** [comment]
@runspired BTW, This dummy app is doing some crazy stuff. I haven't use this addon in a while. I mainly keep it around and up-to-date to catch regressions.

**Pull request merged**
